# 5.16 List 2 Dimensi

List 2 dimensi pada umumnya adalah menempatkan sebuah list di dalam list. Penggambarannya seperti sebuah matrik. Berikut adlah kumpulan contoh dari list 2 dimensi.

In [2]:
matriks = [
    [1,2,3], 
    [2,3,4], 
    [5,6,7]
]
print (matriks)

[[1, 2, 3], [2, 3, 4], [5, 6, 7]]


In [3]:
#jika anda ingin mengakses elemen dalam matriks, anda dapat menggunakan tanda kurung siku beserta indexnya agar dapat mencetak elemen yang diinginkan
matriks [2]

[5, 6, 7]

In [4]:
matriks [0][1] = 7
print (matriks)

[[1, 7, 3], [2, 3, 4], [5, 6, 7]]


In [5]:
for baris in matriks:
    print (baris)
    for kolom in baris:
        print (kolom)

[1, 7, 3]
1
7
3
[2, 3, 4]
2
3
4
[5, 6, 7]
5
6
7


In [32]:
matriks

[[1, 7, 3], [2, 3, 4], [5, 6, 7]]

In [7]:
NIM = [
    [2208541019],
    [2208541032],
    [2208541029]
]
print (NIM)

[[2208541019], [2208541032], [2208541029]]


In [8]:
NIM [0]

[2208541019]

In [9]:
NIM [1]

[2208541032]

In [10]:
prodi_fmipa = [
    ['matematika','biologi','fisika','kimia','farmasi','informatika'],
    ['A','B','A','B','B','B']
]
print (prodi_fmipa)

[['matematika', 'biologi', 'fisika', 'kimia', 'farmasi', 'informatika'], ['A', 'B', 'A', 'B', 'B', 'B']]


In [11]:
print (prodi_fmipa [0][1]) #pada percobaan ini akan mencetak elemen pada baris pertama dan kolom kedua
print (prodi_fmipa [1][1]) #pada percobaan ini akan mencetak elemen pada baris kedua dan kolom kedua

biologi
B


In [12]:
print (prodi_fmipa [0][0]) #pada percobaan ini akan mencetak pada baris pertama dan kolom pertama
print (prodi_fmipa [1][4]) #pada percobaan ini akan mencetak pada baris kedua dan kolom keempat

matematika
B


In [13]:
#cara untuk memanggil anggota pada list dua dimensi
for baris in prodi_fmipa:
    print (baris)
    for kolom in baris:
        print (kolom)

['matematika', 'biologi', 'fisika', 'kimia', 'farmasi', 'informatika']
matematika
biologi
fisika
kimia
farmasi
informatika
['A', 'B', 'A', 'B', 'B', 'B']
A
B
A
B
B
B


# 5.17 Tuples

Tuples mirip dengan list, akan tetapi tuples tidak dapat dirubah isinya. Jika kita memiliki data yang tidak ingin dirubah isinya, kita gunakan tuples, sedangkan jika datanya masih ingin dimanipulasi kedepannya, gunakan list. Perbedaan lain yang bisa kita lihat dari tipe data tuples dan tipe data list adalah cara penulisannya. Pada tipe data tuples itu menggunakaan tanda kurung biasa dalam  menempatkan nila/anggota/elemen. Berikut ini adalah contoh penerapan tuples dalam python.

In [40]:
angka = (0,1,1,3,4,5)
#nah untuk mengakses nilai tuples kita bisa menggunakan indeks.
#penulisannya seperti print (nama_tuples[indeks_ke]) indeks ini dimulai dari 0 untuk mengakses anggota pertama.Selain itu kita juga bisa menggunakan nilai min(-) contohnya seperti (-1) itu akan mencetak nilai paling akhir.
print (angka[0])
print (angka[-1])

0
5


In [41]:
#pada percobaan ini kita bisa menggunakan untuk mengakses nilai tuple berdasarkan range anggota menggunakan tanda (:)
print (angka [0:3]) #akan mencetak nilai tuples ke 1 sampai dengan ke 3
print (angka [2:4]) #akan mencetak nilai tuples ke 3 sampai ke 4

(0, 1, 1)
(1, 3)


In [42]:
for isi in angka [0:3]:
    print (isi)

0
1
1


In [43]:
angka[0] = 10

TypeError: 'tuple' object does not support item assignment

In [44]:
angka.append (10)

AttributeError: 'tuple' object has no attribute 'append'

In [45]:
angka.remove(5)

AttributeError: 'tuple' object has no attribute 'remove'

In [46]:
angka.count(1)

2

In [47]:
angka.index(3)

3

In [48]:
nama = ('hikmah','hani','adin')
print (nama)

('hikmah', 'hani', 'adin')


In [49]:
print (nama[2])

adin


In [50]:
nama [0] = ('indah')

TypeError: 'tuple' object does not support item assignment

In [51]:
nama.count('hikmah')

1

In [52]:
nama.remove ('hikmah')

AttributeError: 'tuple' object has no attribute 'remove'

# 5.18 Dictionaries

Dictionaries digunakan jika data nya terkait satu sama lain. Misalnya data seseorang yang terdiri dari umur, nama, tanggal lahir merupakan satu kesatuan data yang bersumber dari orang tersebut. Pada data dictionaries ini merupakan nilai yang menggunakan key dan value, maka setiap key dipisahkan dari valuenya dengan tanda (:), untuk setiap nilainya dipisahkan dengan tanda (,), dan pada awal dan akhir dari data dictionaries ini dibungkus dengan menggunakan tanda ({}). Nah, apasi itu key dan value? jadi key itu merupakan nama atribut suatu item pada dictionaries, sedangkan value itu merupakan nilai yang disimpan pada suatu atribut. Berikut ini adalah contoh penerapan dictionaries pada python.

In [53]:
#pada data dictionaries untuk nilai dari valuenya bisa diisi dengan tipe data apapun contohnya seperti string, list, boolean, dll.
#sedangkan untuk nilai dari keynya harus berupa data yang tidak berubah seperti string. 
data_orang = {
    "nama" : "Ketut Dogler",
    "umur" : 12,
    "apakah_single" : False
}
print (data_orang)
#nah dapat kita lihat pada percobaan di atas terdapat contoh dictionaries dengan nama (data_orang) yang berisikan (nama, umur, apakah_single)itu semua merupakan kunci (key) yang bisa kita gunakan untuk mengakses value yang ada didalamnya

{'nama': 'Ketut Dogler', 'umur': 12, 'apakah_single': False}


In [54]:
#terdapat dua cara untuk mencetak nilai dictinaries 
#cara yang pertama dengan menggunkaan kurung siku [key] dengan menambahkan key didalamnya.
#cara yang kedua dengan menggunakan fungsi get(key).
print (data_orang ['nama']) #dengan cara [key]
print (data_orang.get ('nama')) #dengan cara get(key)

Ketut Dogler
Ketut Dogler


In [55]:
print (data_orang.get ('tanggal_lahir'))

None


In [56]:
print (data_orang.get ('tanggal_lahir', '02-02-2010'))

02-02-2010


In [57]:
print (data_orang)

{'nama': 'Ketut Dogler', 'umur': 12, 'apakah_single': False}


In [58]:
print (data_orang ["tanggal_lahir"])

KeyError: 'tanggal_lahir'

In [59]:
#pada percobaan ini akan menambahkan dan mengubah nilai dictionariesnya dengan menggunakan cara yang sama
#jika key yang anda definisikan sudah ada, maka akan melakukan proses update
#sedangkan jika key yang anda definisikan tidak ada, maka akan melakukan proses penambahan nilai yang baru
data_orang ['HP'] = '08123456789' #pada percobaan key yang di definisikan tidak ada, maka akan melakukan proses penambhaan pada nilai dictionaresnya
print (data_orang ["HP"])
data_orang ['nama'] = 'Nur Hikmah'
print (data_orang ['nama']) #pada percobaan ini key yang di definisika terdapat pada dictionaris data_orang, maka akan melakukan proses pengubahan(update) nilainya

08123456789
Nur Hikmah


In [60]:
#berikut ini adalah hasil dari proses penambahan dan pengubahan nilai pada dictionariesnya
print (data_orang)

{'nama': 'Nur Hikmah', 'umur': 12, 'apakah_single': False, 'HP': '08123456789'}


In [61]:
data_mahasiswa01 = {
    "Nama" : "Nur Hikmah",
    "NIM"  : "2208541019",
    "Matkul" : "Algoritma",
    "Gender" : "Perempuan"
}
print (data_mahasiswa01)

{'Nama': 'Nur Hikmah', 'NIM': '2208541019', 'Matkul': 'Algoritma', 'Gender': 'Perempuan'}


In [62]:
print ("Nama saya", data_mahasiswa01 ['Nama'])
print ("Saya belajar mata kuliah", data_mahasiswa01 ['Matkul'])

Nama saya Nur Hikmah
Saya belajar mata kuliah Algoritma


In [63]:
print ("Nama saya", data_mahasiswa01.get ('Nama'))
print ("Saya belajar mata kuliah", data_mahasiswa01.get ('Matkul'))

Nama saya Nur Hikmah
Saya belajar mata kuliah Algoritma


In [64]:
data_mahasiswa01 ["Kelas"] = 'A'
print (data_mahasiswa01 ["Kelas"])

A


In [65]:
print (data_mahasiswa01)

{'Nama': 'Nur Hikmah', 'NIM': '2208541019', 'Matkul': 'Algoritma', 'Gender': 'Perempuan', 'Kelas': 'A'}


In [66]:
data_mahasiswa01.pop("Gender")

'Perempuan'

In [67]:
print (data_mahasiswa01)

{'Nama': 'Nur Hikmah', 'NIM': '2208541019', 'Matkul': 'Algoritma', 'Kelas': 'A'}


In [68]:
print (data_mahasiswa01 ["Gender"])

KeyError: 'Gender'

# 5.19 Fungsi dalam Python

Sampai sejauh ini tanpa disadari kita telah menerapkan beberapa jenis fungsi pada Python seperti fungsi input, print, len, range, dll. Pada dasarnya fungsi dibentuk untuk menghidari pengulangan pembuatan program secara manual dimana fungsi tersebut memiliki pengulangan yang tinggi dalam program yang kita buat. Jadi untuk mempermudah dan meringkas program yang kita buat, setiap fungsi tersebut dibutuhkan tinggal kita panggil. 

In [70]:
def full_name (first_name,last_name):
    print(f"Nama lengkapnya adalah {first_name} {last_name}")

In [107]:
first_name = input("Nama depan anda adalah ")
last_name  = input("Nama belakang anda adalah ")
full_name(first_name,last_name)

Nama depan anda adalah Nur
Nama belakang anda adalah Hikmah
Nama lengkapnya adalah Nur Hikmah


In [108]:
def riwayat_hidup (nama, umur, status):
    print (f"Riwayat hidup seorang mahasiswa dengan nama {nama} berumur  {umur} berstatus sebagai {status}")

In [109]:
nama = input ("Nama saya ")
umur = input ("Saya berumur ")
status = input ("Saya berstatus sebagai ")
riwayat_hidup (nama,umur,status)

Nama saya Nur Hikmah
Saya berumur 19 tahun
Saya berstatus sebagai mahasiswa
Riwayat hidup seorang mahasiswa dengan nama Nur Hikmah berumur  19 tahun berstatus sebagai mahasiswa


### 5.19.1 Tugas Fungsi pada Python

Fungsi pada python memiliki dua jenis tugas yaitu:
1. Menjalankan perintah.
2. Menampilkan hasil perhitungan

In [75]:
def waktu_sampai(jarak,kecepatan):
    waktu = jarak/kecepatan
    print(waktu)

In [76]:
def waktu_tempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return waktu

In [77]:
waktu_sampai (80,60)

1.3333333333333333


In [78]:
waktu_tempuh (80,60)

1.3333333333333333

In [111]:
a = waktu_sampai (80,60)
print (a)

1.3333333333333333
None


In [80]:
b = waktu_tempuh(80,60)
print (b)

1.3333333333333333


In [93]:
def luas_segitiga(alas,tinggi):
    luas = (alas * tinggi) / 2
    print ("Luas segitiganya adalah ", luas)

In [94]:
luas_segitiga (3,6)

Luas segitiganya adalah  9.0


In [95]:
a = luas_segitiga (3,6)
print (a)

Luas segitiganya adalah  9.0
None


In [98]:
def luas_segitiga(alas,tinggi):
    luas = (alas * tinggi) / 2
    return luas

In [99]:
luas_segitiga (3,6)

9.0

In [101]:
a = luas_segitiga (3,6)
print (a)

9.0


In [112]:
def luas_persegi_panjang(panjang,lebar):
    luas = (panjang * lebar)
    return luas

In [113]:
luas_persegi_panjang (8,2)

16

# 5.20 Numpy

Numpy merupakan salah satu Library dalam Python yang memiliki keunggulan dalam perhitungan menggunakan vektor dan matrik dalam berbagai dimensi. Hal pertama yang perlu dilakukan adalah memanggil Library Numpy sebagai berikut:


In [3]:
import numpy as np

### 5.20.1 Perintah Dasar pada Numpy

Berikut akan dipaparkan mengenai beberapa perintah dalam Numpy diantaranya memanggil Numpy, mengetahui dimensi dan ukuran variabel. 

In [3]:
a = np.array ([0,1,2,3,4])
print (a)

[0 1 2 3 4]


In [4]:
b = np.array ([[5,6,7,8],[9,8,7,6]])
print (b)

[[5 6 7 8]
 [9 8 7 6]]


In [5]:
c = np.array ([[[0,1,2,3],[4,5,6,7]],
              [[8,9,8,7],[6,5,4,3]],
              [[1,2,3,4],[5,6,7,8]]])
print (c)

[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [6]:
#pada konsep iini menunjukkan bahwa dari matriks (a,b,c) memiliki baris masing-masing (1,2,3)
print (a.ndim)
print (b.ndim)
print (c.ndim)

1
2
3


In [7]:
#konsep shape ini digunakan untuk menggambarkan siensi atau ukuran dari sebuah array atau matriks
#Dalam NumPy, shape mengacu pada jumlah baris dan kolom dalam suatu array atau matriks. Shape dinyatakan sebagai tuple berisi dua bilangan bulat, yaitu (n_baris, n_kolom), yang menunjukkan jumlah baris dan kolom dalam array.
print (a.shape)
print (b.shape)
#pada matriks c ini akan membentuk shape (3,2,4)
 #dimana 3 tersebut menunjukkan bahwa 'c' memiliki 3 matriks di dalamnya
 #dimana 2 tersebut menunjukkan bahwa  setiap matriks 'c' memiliki 2 baris
 #dimana 4 tersebut menunjukkan bahwa setiap matriks 'c' memiliki 4 kolom
print (c.shape)

(5,)
(2, 4)
(3, 2, 4)


### 5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy

In [4]:
d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print (d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
d[0,3]

4

In [6]:
print (d[:,2]) #akan mencetak matriks pada kolom 3
print (d[1,:]) #akan mencetak matriks pada baris ke 2
print (d[0,1:3])#Ini memanggil anggota pada baris ke 0 dan kolom ke 1 hingga ke 2 dari array d. 
print (d[0,0:3:2])

[ 3  7 11]
[5 6 7 8]
[2 3]
[1 3]


### 5.20.3 Matrix pada Numpy

In [12]:
np.ones ((2,3)) #merupakan syntax yang digunakan untuk mencetak makriks yang hanya memiliki anggota angka 1 saja

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.zeros ((3,2))#merupakan syntax yang digunakan untuk mencetak matriks yang hanya memiliki anggota angka 0 saja

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.identity(4)#merupakan syntax yang digunakan untuk mencetak matriks identitas

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [16]:
np.full((3,2),9)

array([[9, 9],
       [9, 9],
       [9, 9]])

In [17]:
np.random.rand(4,3)

array([[0.71603913, 0.67953553, 0.24035459],
       [0.18972362, 0.94360009, 0.77289232],
       [0.37796883, 0.04915331, 0.51546362],
       [0.55505142, 0.1649514 , 0.82618812]])

In [18]:
np.random.randint(1,10,size=(3,4))

array([[5, 7, 1, 5],
       [3, 4, 1, 8],
       [6, 9, 6, 3]])

In [19]:
a = np.zeros((10,10))
print (a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [20]:
b = np.identity (10)
print (b)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [21]:
c = 9*b
print (c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 9. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 9. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 9. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [22]:
d = np.ones((8,8))
e = np.identity(8)*8
f = d+e
print (f)

[[9. 1. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 1. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 1. 9. 1. 1. 1.]
 [1. 1. 1. 1. 1. 9. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 1.]
 [1. 1. 1. 1. 1. 1. 1. 9.]]


In [23]:
c[1:-1,1:-1] = f
print (c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 9. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 9. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 9. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 9. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [24]:
g = np.identity(6)*9
c[2:-2,2:-2] = g
print (c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 9. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 9. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [25]:
h = np.ones ((4,4))*2
i = np.identity(4)* 7
j = h + i
print(j)

[[9. 2. 2. 2.]
 [2. 9. 2. 2.]
 [2. 2. 9. 2.]
 [2. 2. 2. 9.]]


In [26]:
c[3:-3,3:-3] = j
print (c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 9. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 9. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [27]:
k = np.identity(2)*9
c [4:-4,4:-4] = k
print (c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 2. 2. 2. 0. 1. 0.]
 [0. 1. 0. 2. 9. 0. 2. 0. 1. 0.]
 [0. 1. 0. 2. 0. 9. 2. 0. 1. 0.]
 [0. 1. 0. 2. 2. 2. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


### 5.20.4 Copy pada Numpy

Sering sekali kita menduplikat suatu variabel dengan maksud untuk mempercepat pekerjaan kita. Akan tetapi sering tanpa disadari ikatan persamaan dalam Numpy sedemikian eratnya sehingga saat anggota variabel baru dirubah, dampaknya juga akan merubah variabel asal. Untuk menghindari perubahan variabel awal yang tidak dikehendaki maka diperlukan perintah copy.

In [7]:
a = np.array ([1,2,3,4,5])
print (a)

[1 2 3 4 5]


In [8]:
b = a
print (b)

[1 2 3 4 5]


In [9]:
b[0] = 10
print (b)

[10  2  3  4  5]


In [10]:
print (a)

[10  2  3  4  5]


In [12]:
c = np.array ([1,2,3,4,5])
print (c)

[1 2 3 4 5]


In [13]:
d = c.copy()
print (d)

[1 2 3 4 5]


In [14]:
d [0] = 10 
print (d)

[10  2  3  4  5]


In [15]:
print (c)

[1 2 3 4 5]


In [16]:
c = np.array ([[[0,1,2,3],[4,5,6,7]],
              [[8,9,8,7],[6,5,4,3]],
              [[1,2,3,4],[5,6,7,8]]])
print (c)

[[[0 1 2 3]
  [4 5 6 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [17]:
c [0,1:2] = 7
print (c)

[[[0 1 2 3]
  [7 7 7 7]]

 [[8 9 8 7]
  [6 5 4 3]]

 [[1 2 3 4]
  [5 6 7 8]]]


### 5.20.5 Operasi Matematika pada Numpy

In [18]:
a+2

array([12,  4,  5,  6,  7])

In [19]:
a-2

array([8, 0, 1, 2, 3])

In [20]:
a*2

array([20,  4,  6,  8, 10])

In [21]:
a/2

array([5. , 1. , 1.5, 2. , 2.5])

In [22]:
a**2

array([100,   4,   9,  16,  25], dtype=int32)

In [23]:
b = np.array ([6,7,8,9,10])
print (b)

[ 6  7  8  9 10]


In [25]:
b = np.array ([6,7,8,9,10])
print (b)

[ 6  7  8  9 10]


In [26]:
a+b

array([16,  9, 11, 13, 15])

In [27]:
a-b

array([ 4, -5, -5, -5, -5])

In [28]:
a*b

array([60, 14, 24, 36, 50])

In [29]:
a/b

array([1.66666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [30]:
a**b

array([1000000,     128,    6561,  262144, 9765625], dtype=int32)

In [32]:
a//b

array([1, 0, 0, 0, 0], dtype=int32)

In [33]:
np.cos (a)

array([-0.83907153, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [34]:
np.sin (a)

array([-0.54402111,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [35]:
np.tan(a)

array([ 0.64836083, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [38]:
#untuk menghitung hiperbolik dari suatu array dapat menggunakan dengan operasi berikut ini
print (np.sinh(a))
print (np.cosh(a))
print (np.tanh(a))

[1.10132329e+04 3.62686041e+00 1.00178749e+01 2.72899172e+01
 7.42032106e+01]
[1.10132329e+04 3.76219569e+00 1.00676620e+01 2.73082328e+01
 7.42099485e+01]
[1.         0.96402758 0.99505475 0.9993293  0.9999092 ]


In [39]:
np.sqrt(a) #untuk menghitung dengan operasi akar

array([3.16227766, 1.41421356, 1.73205081, 2.        , 2.23606798])

### 5.20.6 Perkalian Matrik pada Numpy

Dapat diamati bahwa operasi matematika pada suatu matrik dengan Numpy akan mengoperaikan elemen yang baris dan kolomnya sama. Tentunya hal ini akan memberikan hasil berbeda jika yang kita kehendaki adalah perkalian dua matrik. Perkalian matrik pada Numpy dapat menggunakan perintah matmul. Perlu dijadikan perhatian tentang ukuran matrik yang akan dikalikan harus sesuai dengan persyaratan. Misalnya matrik ukuran (2x3) dapat dikalikan dengan matrik ukuran (3x4).

In [45]:
a = np.array ([[1,2,3,4],[5,6,7,8]])
print (a)

[[1 2 3 4]
 [5 6 7 8]]


In [46]:
b = np.array ([[9,10,11,12], [13,14,15,16]])
print (b)

[[ 9 10 11 12]
 [13 14 15 16]]


In [47]:
c = a*b
print (c)

[[  9  20  33  48]
 [ 65  84 105 128]]


In [56]:
d = np.matmul(a, b)
print (d)

[[211 230 249 268]
 [255 278 301 324]
 [299 326 353 380]
 [343 374 405 436]]


In [58]:
e = np.array ([[9,10],[11,12],[13,14],[15,16]])
print (e)

[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [59]:
f = np.matmul(a, e)
print (f)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)

In [61]:
g = a*e
print (g)

[[ 81 100]
 [121 144]
 [169 196]
 [225 256]]


### 5.20.7 min, max, dan sum pada Numpy

Perintah min, max dan sum cukup sering digunakan untuk mengetahui nilai minimum, maksimum dan penjumlahan.

In [63]:
a = np.array ([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [65]:
b = np.min(a)
print (b)

1


In [75]:
#parameter opsional axis ini digunakan untuk menentukan dimensi mana yang akan diambil nilai minimumnya
c = np.min (a,axis = 0)
print (c)
d = np.min (a,axis=1)
print (d)

[1 2 3 4]
[1 5 9]


In [69]:
e = np.max(a)
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [70]:
f = np.max(a,axis=0)
print (f)

[ 9 10 11 12]


In [71]:
g = np.max (a,axis=1)
print (g)

[ 4  8 12]


In [72]:
h = np.sum(a,axis=0)
print (h)

[15 18 21 24]


In [76]:
i = np.sum(a,axis=1)
print(i)

[10 26 42]
